# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=26.1.2-1.0.0
group=com.warpgames.voltaicforgery
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Voltaic Forgery
mod_author=WarpGamesTV
mod_id=voltaicforgery
license=CC0-1.0
credits=
description=This is a take on tool making for 26.1+.
minecraft_version_range=[26.1, 26.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.145.4+26.1.2
fabric_loader_version=0.18.6
fabric_minecraft_version_range=>=26.1 <26.2

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.7-beta
neoforge_version_range=[26.1,)
neoforge_loader_version_range=[4,)

# JEI, see https://maven.blamejared.com/mezz/jei/
jei_version=29.5.0.26

# EMI, see https://maven.terraformersmc.com/
emi_version=1.1.22+1.21.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
